import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createServer } from "../eventSimulator/server.mjs";
import { createEngine } from "../eventSimulator/engine.mjs";

const statePath = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "event-simulator-http-")), "state.json");
process.env.EVENT_SIMULATOR_STATE = statePath;
const server = createServer({ simulator: createEngine({ root: path.resolve("."), statePath }) });
await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
const port = server.address().port;
const url = (path) => `http://127.0.0.1:${port}${path}`;
const get = async (path) => (await fetch(url(path))).json();
const post = async (path, value = {}) => (await fetch(url(path), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(value) })).json();

const controlHtml = await (await fetch(url("/"))).text();
assert.match(controlHtml, /id="buildHash"/);
assert.doesNotMatch(controlHtml, /__BUILD_HASH__/);
assert.match(controlHtml, /Build: local checkout \/ [0-9a-f]{7,40}/);

assert.equal((await get("/state")).cursor, -1);
assert.equal((await get("/api/tba/event/2026evsim/teams")).length, 55);
assert.equal((await get("/api/tba/event/2026evsim/matches")).length, 0);
assert.equal((await get("/api/tba/event/2026evsim/rankings")).rankings.length, 0);
await post("/control/advance");
const scheduled = await get("/api/tba/event/2026evsim/matches");
assert.ok(scheduled.length > 0);
assert.equal(scheduled[0].alliances.red.score, -1);
assert.equal((await get("/api/tba/event/2026evsim/oprs")).oprs && Object.keys((await get("/api/tba/event/2026evsim/oprs")).oprs).length, 0);
await post("/control/advance");
assert.equal((await get("/api/statbotics/v3/event/2026evsim")).key, "2026evsim");
assert.equal((await get("/api/statbotics/v3/matches/2026evsim")).length, 1);
assert.equal((await get("/api/statbotics/v3/team_matches/2026evsim")).length, 6);
assert.equal((await get("/api/scouting/2026evsim")).meta.eventKey, "2026evsim");
const offsetState = await post("/control/set", { cursor: 1, offsets: { scouting: 2 } });
assert.equal(offsetState.offsets.scouting, 2);
assert.equal((await get("/api/scouting/2026evsim")).entries.length > 0, true);
await post("/control/set", { failures: { scouting: "failed" } });
assert.equal((await fetch(url("/api/scouting/2026evsim"))).status, 503);
const resetState = await post("/control/reset");
assert.equal(resetState.cursor, -1);
assert.equal(resetState.phase, "team-only");
assert.deepEqual(resetState.requests, []);
await get("/api/tba/event/2026evsim/teams");
await get("/api/tba/event/2026evsim/teams");
const coalesced = await get("/state");
assert.equal(coalesced.requests.length, 1);
assert.equal(coalesced.requests[0].repeatCount, 2);
assert.equal("signature" in coalesced.requests[0], false);
assert.equal("dataSignature" in coalesced.requests[0], false);
const cors = await fetch(url("/state"));
assert.equal(cors.headers.get("access-control-allow-origin"), "*");
await new Promise((resolve) => server.close(resolve));
console.log("PASS event simulator HTTP");
