import assert from "node:assert/strict";
import fs from "node:fs";
assert.equal(fs.existsSync("scripts/start-event-simulator.ps1"), true);
assert.match(fs.readFileSync("scripts/start-event-simulator.ps1", "utf8"), /RoutingMode/);
assert.match(fs.readFileSync("scripts/start-event-simulator.ps1", "utf8"), /__LOCAL_BUILD_HASH/);
assert.match(fs.readFileSync("scripts/start-event-simulator.ps1", "utf8"), /health check/);
assert.match(fs.readFileSync("scripts/start-localhost.ps1", "utf8"), /firebase\.cmd/);
assert.match(fs.readFileSync("scripts/start-localhost.ps1", "utf8"), /-lt 60/);
assert.match(fs.readFileSync("scripts/start-localhost.ps1", "utf8"), /ProcessName -in/);
assert.match(fs.readFileSync("scripts/stop-localhost.ps1", "utf8"), /ProcessName -in/);
assert.match(fs.readFileSync("index.html", "utf8"), /deployment-revision\.local\.js\?revision=event-simulator-runtime-9/);
assert.equal(fs.existsSync(".browser-test/verify-event-simulator.mjs"), true);
assert.equal(fs.existsSync("docs/event-simulator-human-checklist.md"), true);
assert.match(fs.readFileSync("eventSimulator/control.html", "utf8"), /Show setup instructions/);
assert.match(fs.readFileSync("eventSimulator/control.html", "utf8"), /start-event-simulator\.ps1/);
assert.match(fs.readFileSync("eventSimulator/control.html", "utf8"), /2026evsim/);
assert.match(fs.readFileSync("eventSimulator/control.html", "utf8"), /id="advance"/);
assert.match(fs.readFileSync("eventSimulator/control.html", "utf8"), /id="state" aria-label="Simulator event log"/);
assert.match(fs.readFileSync("eventSimulator/control.html", "utf8"), /class="reset-controls"/);
assert.match(fs.readFileSync("eventSimulator/control.html", "utf8"), /renderState\(await response\.json\(\)\)/);
assert.match(fs.readFileSync("eventSimulator/control.html", "utf8"), /__BUILD_HASH__/);
console.log("PASS event simulator launcher artifacts");
