import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createEngine, rewriteEventKeys } from "../eventSimulator/engine.mjs";

const root = path.resolve(".");
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "event-simulator-"));
const engine = createEngine({ root, statePath: path.join(temp, "state.json") });

assert.equal(engine.getState().phase, "team-only");
assert.equal(engine.getState().currentMatch, "Pre-Event");
assert.deepEqual(engine.getState().offsets, { tba: 0, statbotics: -2, scouting: -1 });
engine.setState({ offsets: { tba: 0, statbotics: 0, scouting: 0 } });
assert.equal(engine.get("tba", "teams").some((team) => team.team_number === 4638), true);
assert.equal(engine.get("tba", "matches").length, 0);
assert.deepEqual(engine.get("tba", "alliances"), []);
engine.advance();
assert.equal(engine.getState().phase, "scheduled");
assert.equal(engine.getState().currentMatch, "Schedule Released");
assert.ok(engine.get("tba", "matches").every((match) => match.alliances.red.score === -1));
assert.equal(engine.get("statbotics", "matches").length, 0);
engine.advance();
assert.equal(engine.getState().currentMatch, "Qual 1");
const first = engine.get("tba", "matches").filter((match) => match.alliances.red.score >= 0);
assert.equal(first.length, 1);
assert.equal(first[0].event_key, "2026evsim");
assert.equal(engine.get("statbotics", "matches").length, 1);
assert.equal(engine.get("statbotics", "team-matches").length, 6);
assert.equal(engine.get("statbotics", "event").current_match, 1);
assert.equal(engine.get("statbotics", "team-events").some((row) => row.team === 4638), false);
engine.setState({ cursor: -1 });
assert.equal(engine.get("scouting", "scouting").entries.length, 0);
engine.setState({ cursor: 1, offsets: { scouting: 0 } });
const scouting = engine.get("scouting", "scouting");
assert.equal(scouting.meta.eventKey, "2026evsim");
assert.equal(scouting.schema.schemaId, "2026-match-v1");
assert.ok(scouting.schema.expectedScoutingFields.includes("autoFuelPct"));
assert.ok(scouting.entries.every((entry) => Number(entry.matchNumber) === Number(scouting.entries[0]?.matchNumber)));
assert.equal(scouting.entries.some((entry) => entry.teamNumber === 4638), false);
engine.setState({ failures: { scouting: "empty" } });
assert.equal(engine.get("scouting", "scouting").entries.length, 0);
engine.setState({ failures: { scouting: "malformed" } });
assert.equal(engine.get("scouting", "scouting").malformed, true);
engine.setState({ failures: { scouting: null }, corrections: [{ source: "scouting", cursor: 1, path: "meta.eventKey", value: "corrected-event" }] });
assert.equal(engine.get("scouting", "scouting").meta.eventKey, "corrected-event");
assert.equal(engine.get("tba", "rankings").rankings.length, 6);
assert.equal(engine.get("tba", "oprs").oprs["frc4638"], undefined);
assert.equal(engine.get("tba", "oprs").oprs[first[0].alliances.red.team_keys[0]] > 0, true);
engine.setState({ cursor: engine.getState().totalSequence });
assert.equal(engine.get("tba", "oprs").oprs["frc4638"], undefined);
assert.equal(engine.get("tba", "rankings").rankings.some((row) => row.team_key === "frc4638"), false);
const qualificationCount = engine.fixtures.tbaMatches.filter((match) => match.comp_level === "qm").length;
engine.setState({ cursor: qualificationCount });
const scheduledPlayoffs = engine.get("tba", "matches").filter((match) => match.comp_level !== "qm");
assert.equal(scheduledPlayoffs.length > 0, true);
assert.equal(scheduledPlayoffs.every((match) => match.alliances.red.score === -1 && match.alliances.blue.score === -1), true);
assert.equal(scheduledPlayoffs.filter((match) => match.comp_level === "sf" && match.set_number <= 4).every((match) => match.alliances.red.team_keys.length > 0 && match.alliances.blue.team_keys.length > 0), true);
assert.equal(scheduledPlayoffs.filter((match) => match.comp_level === "sf" && match.set_number > 4).every((match) => match.alliances.red.team_keys.length === 0 && match.alliances.blue.team_keys.length === 0), true);
assert.equal(scheduledPlayoffs.filter((match) => match.comp_level === "f").every((match) => match.alliances.red.team_keys.length === 0 && match.alliances.blue.team_keys.length === 0), true);
assert.equal(engine.get("tba", "alliances").length, 8);
assert.equal(engine.get("tba", "alliances")[0].picks.length, 4);
engine.setState({ cursor: qualificationCount + 1 });
assert.equal(engine.get("tba", "matches").some((match) => match.comp_level !== "qm"), true);
engine.setState({ cursor: qualificationCount + 13 });
assert.equal(engine.getState().currentMatch, "Semis 13-1");
const completedSemis = engine.get("tba", "matches").filter((match) => match.comp_level === "sf" && match.alliances.red.score >= 0);
assert.equal(completedSemis.length, 13);
assert.equal(engine.get("tba", "matches").filter((match) => match.comp_level === "f" && match.alliances.red.score >= 0).length, 0);
engine.setState({ cursor: -1, offsets: { tba: 2, statbotics: -1, scouting: 1 }, latencyMs: { tba: 12 }, delayScale: 0.5, corrections: [{ source: "tba", cursor: 1, path: "event.name", value: "Corrected" }] });
assert.equal(engine.effectiveCursor("tba"), 1);
assert.equal(engine.effectiveCursor("statbotics"), -1);
assert.equal(engine.get("tba", "event").name, "Corrected");
assert.equal(engine.resetTimeline().cursor, -1);
assert.equal(engine.resetConfig().currentMatch, "Pre-Event");
assert.equal(engine.getState().cursor, -1);
engine.setState({ cursor: 4 });
const preResetGeneration = engine.requestGeneration();
engine.recordRequest({ source: "tba", kind: "matches", cursor: 4 }, preResetGeneration);
assert.equal(engine.resetAll().currentMatch, "Pre-Event");
assert.equal(engine.getState().cursor, -1);
engine.recordRequest({ source: "tba", kind: "matches", cursor: 4 }, preResetGeneration);
assert.deepEqual(engine.getState().requests, []);
engine.recordRequest({ source: "tba", kind: "teams", cursor: -1 });
assert.equal(engine.getState().requests.length, 1);
engine.recordRequest({ source: "tba", kind: "teams", cursor: -1, at: "2026-08-14T00:00:01.000Z" });
assert.equal(engine.getState().requests.length, 1);
assert.equal(engine.getState().requests[0].repeatCount, 2);
assert.equal(engine.getState().requests[0].at, "2026-08-14T00:00:01.000Z");
engine.recordRequest({ source: "tba", kind: "teams", cursor: -1, at: "2026-08-14T00:00:02.000Z", dataSignature: "changed" });
assert.equal(engine.getState().requests.length, 1);
assert.equal(engine.getState().requests[0].repeatCount, 3);
assert.equal(engine.getState().requests[0].cursor, -1);
assert.equal("signature" in engine.getState().requests[0], false);
assert.equal("dataSignature" in engine.getState().requests[0], false);
assert.equal(rewriteEventKeys({ key: "2026chcmp_qm1", url: "x/2026chcmp" }, "2026chcmp", "2026evsim").key, "2026evsim_qm1");
console.log("PASS event simulator engine");
